import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../../public/sass/helper/base.scss';
import '../../public/sass/helper/reset.scss';
import '../../public/sass/helper/helper.scss';
import Footer from "./components/Footer";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nature Grooming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="pb_scroll" className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
{/* <section className='header_section'>
    <Container>
        <Row>
            <Col xxl={12} xl={12} lg={12} md={12} sm={12} xs={12}>
                <div className='parent_area'></div>
            </Col> 
        </Row>
    </Container>
</section> */}